<a href="https://colab.research.google.com/github/19PA1A0245/AI-Lab/blob/master/experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 1 : Numpy

##i)Different ways to create a NumPy arrays

###a)create a numpy array using a list

In [1]:
import numpy as np
x = np.array([[2,4,5],[6,7,8]])
print(x)

[[2 4 5]
 [6 7 8]]


##ii)Add,remove,modify elements in an array

###Add

In [2]:
p=np.array([2,4,5])
q=np.append(p,[6,7,8])
print(q)

[2 4 5 6 7 8]


###Remove

In [16]:
x=np.delete(p,2)
print(x)

[1 2 4]


###Modify

In [8]:
x[x>5]=-1
print(x)

[2 4]


##iii)Arthematic operations on Numpy array

In [12]:
import numpy as np
p=np.random.random((3,3))
q=np.random.random((3,3))
num_sum=np.add(p,q)
num_diff=np.subtract(p,q)
num_prod=np.multiply(p,q)
num_quo=np.divide(p,q)
num_mod=np.mod(p,q)
num_pow=np.power(p,q)
print(num_sum)
print(num_diff)
print(num_prod)
print(num_quo)
print(num_mod)
print(num_pow)


[[0.82948286 1.36601552 0.71700642]
 [1.58841664 0.85925457 0.97384643]
 [0.96665946 1.45589421 1.1867166 ]]
[[ 0.11599905  0.51429813 -0.4097391 ]
 [ 0.11920741  0.26144376  0.2480446 ]
 [-0.91720743 -0.51279381 -0.72131527]]
[[0.16864651 0.40037396 0.08655302]
 [0.62721426 0.1674914  0.22171268]
 [0.02329026 0.46416761 0.22200015]]
[[1.32516238 2.20767318 0.27270339]
 [1.16227425 1.87467056 1.68350502]
 [0.02625028 0.4790502  0.24391696]]
[[0.11599905 0.08843943 0.15363366]
 [0.11920741 0.26144376 0.2480446 ]
 [0.02472601 0.4715502  0.23270067]]
[[0.76546347 0.97406315 0.34808763]
 [0.89038617 0.84103284 0.83625765]
 [0.03065195 0.47713269 0.24883694]]


##iv)Slicing and iterating of Numpy arrays





###Slicing

In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:7])

[2 3 4 5 6 7]


###Iterating

In [17]:
for x in arr:
  print(x)

1
2
3
4
5
6
7


##v)Matirx operations on Numpy arrays

In [15]:
import numpy as np
p=np.array([[1,2],[3,4]])
q=np.array([[5,6],[7,8]])
print(np.add(p,q))
print(np.subtract(p,q))
print(np.divide(p,q))


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
